//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.04 at 08:39:08 PM HST 
//


package edu.hawaii.myisern.organizations.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.hawaii.myisern.organizations.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _HomePage_QNAME = new QName("", "Home-Page");
    private final static QName _AffiliatedResearcher_QNAME = new QName("", "Affiliated-Researcher");
    private final static QName _Type_QNAME = new QName("", "Type");
    private final static QName _Contact_QNAME = new QName("", "Contact");
    private final static QName _ResearchDescription_QNAME = new QName("", "Research-Description");
    private final static QName _ResearchKeyword_QNAME = new QName("", "Research-Keyword");
    private final static QName _Country_QNAME = new QName("", "Country");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.hawaii.myisern.organizations.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AffiliatedResearchers }
     * 
     */
    public AffiliatedResearchers createAffiliatedResearchers() {
        return new AffiliatedResearchers();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Organizations }
     * 
     */
    public Organizations createOrganizations() {
        return new Organizations();
    }

    /**
     * Create an instance of {@link ResearchKeywords }
     * 
     */
    public ResearchKeywords createResearchKeywords() {
        return new ResearchKeywords();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Home-Page")
    public JAXBElement<String> createHomePage(String value) {
        return new JAXBElement<String>(_HomePage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Affiliated-Researcher")
    public JAXBElement<String> createAffiliatedResearcher(String value) {
        return new JAXBElement<String>(_AffiliatedResearcher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Contact")
    public JAXBElement<String> createContact(String value) {
        return new JAXBElement<String>(_Contact_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Research-Description")
    public JAXBElement<String> createResearchDescription(String value) {
        return new JAXBElement<String>(_ResearchDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Research-Keyword")
    public JAXBElement<String> createResearchKeyword(String value) {
        return new JAXBElement<String>(_ResearchKeyword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

}
