//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.07 at 03:07:12 AM HST 
//


package edu.hawaii.myisern.collaborations.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}Collaborating-Organizations"/>
 *         &lt;element ref="{}Collaboration-Types"/>
 *         &lt;element ref="{}Years"/>
 *         &lt;element ref="{}Outcome-Types"/>
 *         &lt;element ref="{}Description"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "collaboratingOrganizations",
    "collaborationTypes",
    "years",
    "outcomeTypes",
    "description"
})
@XmlRootElement(name = "Collaboration")
public class Collaboration {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Collaborating-Organizations", required = true)
    protected CollaboratingOrganizations collaboratingOrganizations;
    @XmlElement(name = "Collaboration-Types", required = true)
    protected CollaborationTypes collaborationTypes;
    @XmlElement(name = "Years", required = true)
    protected Years years;
    @XmlElement(name = "Outcome-Types", required = true)
    protected OutcomeTypes outcomeTypes;
    @XmlElement(name = "Description", required = true)
    protected String description;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the collaboratingOrganizations property.
     * 
     * @return
     *     possible object is
     *     {@link CollaboratingOrganizations }
     *     
     */
    public CollaboratingOrganizations getCollaboratingOrganizations() {
        return collaboratingOrganizations;
    }

    /**
     * Sets the value of the collaboratingOrganizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollaboratingOrganizations }
     *     
     */
    public void setCollaboratingOrganizations(CollaboratingOrganizations value) {
        this.collaboratingOrganizations = value;
    }

    /**
     * Gets the value of the collaborationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link CollaborationTypes }
     *     
     */
    public CollaborationTypes getCollaborationTypes() {
        return collaborationTypes;
    }

    /**
     * Sets the value of the collaborationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollaborationTypes }
     *     
     */
    public void setCollaborationTypes(CollaborationTypes value) {
        this.collaborationTypes = value;
    }

    /**
     * Gets the value of the years property.
     * 
     * @return
     *     possible object is
     *     {@link Years }
     *     
     */
    public Years getYears() {
        return years;
    }

    /**
     * Sets the value of the years property.
     * 
     * @param value
     *     allowed object is
     *     {@link Years }
     *     
     */
    public void setYears(Years value) {
        this.years = value;
    }

    /**
     * Gets the value of the outcomeTypes property.
     * 
     * @return
     *     possible object is
     *     {@link OutcomeTypes }
     *     
     */
    public OutcomeTypes getOutcomeTypes() {
        return outcomeTypes;
    }

    /**
     * Sets the value of the outcomeTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutcomeTypes }
     *     
     */
    public void setOutcomeTypes(OutcomeTypes value) {
        this.outcomeTypes = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
