//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.04 at 08:39:08 PM HST 
//


package edu.hawaii.myisern.organizations.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}Type"/>
 *         &lt;element ref="{}Contact"/>
 *         &lt;element ref="{}Affiliated-Researchers"/>
 *         &lt;element ref="{}Country"/>
 *         &lt;element ref="{}Research-Keywords"/>
 *         &lt;element ref="{}Research-Description"/>
 *         &lt;element ref="{}Home-Page"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "type",
    "contact",
    "affiliatedResearchers",
    "country",
    "researchKeywords",
    "researchDescription",
    "homePage"
})
@XmlRootElement(name = "Organization")
public class Organization {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "Contact", required = true)
    protected String contact;
    @XmlElement(name = "Affiliated-Researchers", required = true)
    protected AffiliatedResearchers affiliatedResearchers;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "Research-Keywords", required = true)
    protected ResearchKeywords researchKeywords;
    @XmlElement(name = "Research-Description", required = true)
    protected String researchDescription;
    @XmlElement(name = "Home-Page", required = true)
    protected String homePage;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContact(String value) {
        this.contact = value;
    }

    /**
     * Gets the value of the affiliatedResearchers property.
     * 
     * @return
     *     possible object is
     *     {@link AffiliatedResearchers }
     *     
     */
    public AffiliatedResearchers getAffiliatedResearchers() {
        return affiliatedResearchers;
    }

    /**
     * Sets the value of the affiliatedResearchers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffiliatedResearchers }
     *     
     */
    public void setAffiliatedResearchers(AffiliatedResearchers value) {
        this.affiliatedResearchers = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the researchKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchKeywords }
     *     
     */
    public ResearchKeywords getResearchKeywords() {
        return researchKeywords;
    }

    /**
     * Sets the value of the researchKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchKeywords }
     *     
     */
    public void setResearchKeywords(ResearchKeywords value) {
        this.researchKeywords = value;
    }

    /**
     * Gets the value of the researchDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResearchDescription() {
        return researchDescription;
    }

    /**
     * Sets the value of the researchDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResearchDescription(String value) {
        this.researchDescription = value;
    }

    /**
     * Gets the value of the homePage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePage() {
        return homePage;
    }

    /**
     * Sets the value of the homePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePage(String value) {
        this.homePage = value;
    }

}
